### ISSUE TITLE
Motd BUG?

### ISSUE THREAD

**Issue by CrAazZyMaN21** [NiandraL/NiandraMOTD#1]
If I put the motd in my addons folder nothing happens it doesn't open and there is no error in the console. What have i done wrong? Your Motd looks pretty nice good work if it would work!

**Comment by NiandraL** [comment]
Make sure the file path is garrysmod/addons/niandramotd/lua and not  garrysmod/addons/niandramotd/niandramotd/lua

**Comment by CrAazZyMaN21** [comment]
It was always in garrysmod/addons/niandramotd/lua. I dont understand it ulx is also there and it works?!?!?! Its also with the permissions of the user where gmod is running.

**Comment by CrAazZyMaN21** [comment]
I solved it the folder name is NiandraMOTD it should be niandramotd then it works! Thanks <3 love it
